version: "3.7"
services:
  postgres:
    container_name: 'db-postgres'
    image: 'postgres:latest'
    restart: always
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=darshil'
      - 'POSTGRES_DB=mems'
      - 'POSTGRES_PASSWORD=password'
    volumes:
#      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

#volumes:
#  postgres_data:
